version: 2.1

orbs:
  node: circleci/node@2.1.0

jobs:
  build:
    executor:
      name: node/default
      tag: '13'
    steps:
      - checkout
      - node/install-packages
      - run:
          name: release
          command: npm run semantic-release || true
