version: 2.1

orbs:
  node: circleci/node@3.0.0

executors:
  node:
    docker:
      - image: circleci/node:12.8

jobs:
  install-npm-dependencies:
    executor: node
    steps:
      - checkout
      - node/install-packages
      - persist_to_workspace:
          root: ~/project
          paths:
            - node_modules
  lint:
    executor: node
    steps:
      - checkout
      - attach_workspace:
          at: ~/project
      - run:
          name: lint
          command: npm run lint
  release:
    executor: node
    steps:
      - checkout
      - attach_workspace:
          at: ~/project
      - run:
          name: release
          command: npm run semantic-release || true

workflows:
  develop:
    jobs:
      - install-npm-dependencies:
          filters:
            branches:
              only: develop
      - lint:
          requires:
            - install-npm-dependencies
      - test:
          requires:
            - install-npm-dependencies
  master:
    jobs:
      - install-npm-dependencies:
          filters:
            branches:
              only: master
      - lint:
          requires:
            - install-npm-dependencies
      - node/test
      - release:
          requires:
            - lint
            - test
