version: 2.1

orbs:
  node: circleci/node@3.0.0

executors:
  node:
    docker:
      - image: circleci/node:12.8

jobs:
  lint:
    executor: node
    steps:
      - checkout
      - node/install-packages
      - run:
          name: lint
          command: npm run lint
  release:
    executor: node
    steps:
      - checkout
      - node/install-packages
      - run:
          name: release
          command: npm run semantic-release || true

workflows:
  develop:
    jobs:
      - lint:
          filters:
            branches:
              only: develop
      - node/test:
          filters:
            branches:
              only: develop
  master:
    jobs:
      - lint:
          filters:
            branches:
              only: master
      - node/test:
          filters:
            branches:
              only: master
      - release:
          requires:
            - lint
            - node/test
